apiVersion: "pipelinesascode.tekton.dev/v1alpha1"
kind: Repository
metadata:
  name: bvv9r6ihi-java-springboot-gitops-repository
spec:
  url: https://github.com/rhtap-qe-jsmid/bvv9r6ihi-java-springboot-gitops